# Загальна інформація про проєкт
site_name: Документація до Калькулятора
site_author: Ваше Ім'я та Прізвище
site_description: 'Проста та зрозуміла документація для консольного калькулятора.'

# Налаштування зовнішнього вигляду
theme:
  name: material
  language: uk  # Додамо українську мову для елементів інтерфейсу

# Налаштування структури навігаційного меню
nav:
  - Головна: index.md
  - Посібник користувача:
      - Встановлення: docs/guide/installation.md
      - Приклади використання: docs/guide/usage.md
  - Про проєкт: docs/about.md