# Загальна інформація про проєкт
site_name: Dokumentatsiya do Kальkulyatora
site_author: Vashe Ime ta Prizvyshche
site_description: 'Prosta ta zrozumila dokumentatsiya dlya konsolnogo kalkulyatora.'

# Налаштування зовнішнього вигляду
theme:
  name: material
  language: uk  # Додамо українську мову для елементів інтерфейсу

# Налаштування структури навігаційного меню
nav:
  - Holovna: index.md
  - Posibnyk koryshtuacha:
      - Vstanovlennya: docs/guide/installation.md
      - Priklady vykorystannya: docs/guide/usage.md
  - Pro proekt: docs/about.md